project:
  type: website
  output-dir: docs

website:
  title: "Data Analytics and Visualization"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: calendar/calendar.qmd
        text: Calendar
      - text: Syllabus
        menu:
          - href: syllabus/policies.qmd
            text: Policies
          - href: syllabus/rubric.qmd
            text: Grading
      - text: Resources
        menu:
          - href: resources/references.qmd
            text: Reference materials
          - href: resources/software.qmd
            text: Software & tools
          - href: resources/datasets.qmd
            text: Datasets
          - href: https://github.com/gabehope/DataViz-Homework-Template
            text: Homework template
      - text: Links
        menu:
          - href: https://harveymuddcollege.instructure.com/courses/1728
            text: Canvas
          - href: https://www.gradescope.com/courses/839547
            text: Gradescope
      - href: project/project.qmd
        text: Project


format:
  html:
    theme: 
      - cosmo
      - theme.scss
    toc: true