---
title: "Course Calendar"
---

This is the **tentative** course calendar for Data Analytics and Visualization. This calendar is subject to change depending on the pace of the class and student interest.

+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| Lecture  | Date     | Topics                                           | Readings                                                                | Materials                                                                  | Homework                                         |
+==========+==========+==================================================+=========================================================================+============================================================================+==================================================+
| 1        | 8/26     | Course introduction                              | [538](https://projects.fivethirtyeight.com/2024-election-forecast/)     | [Slides](../modules/00-Introduction/lectures/Lecture-0-0/slides-0-0.qmd)   |                                                  |
|          |          |                                                  |                                                                         |                                                                            |                                                  |
|          |          |                                                  |                                                                         | [Handout](../modules/00-Introduction/lectures/Lecture-0-0/handout-0-0.qmd) |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 2        | 8/28     | Tidy data, data types                            | [MDSR 6.1](https://mdsr-book.github.io/mdsr3e/06-dataII.html#tidy-data) | [Slides](../modules/00-Introduction/lectures/Lecture-0-1/slides-0-1.qmd)   |                                                  |
|          |          |                                                  |                                                                         |                                                                            |                                                  |
|          |          |                                                  |                                                                         | [Handout](../modules/00-Introduction/lectures/Lecture-0-1/handout-0-1.qmd) |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
|          | 9/2      |                                                  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 3        | 9/4      | Introduction to visualization                    | [DV ch. 1](https://socviz.co/lookatdata.html#lookatdata)                | [Slides](../modules/00-Introduction/lectures/Lecture-0-2/slides-0-2.qmd)   |                                                  |
|          |          |                                                  |                                                                         |                                                                            |                                                  |
|          |          |                                                  | [MDSR 2.1-2.5](https://mdsr-book.github.io/mdsr3e/02-datavizI.html)     | [Handout](../modules/00-Introduction/lectures/Lecture-0-2/handout-0-2.qmd) |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 4        | 9/9      | Principles for effective visualization           |                                                                         | [Slides](../modules/00-Introduction/lectures/Lecture-0-3/slides-0-3.qmd)   |                                                  |
|          |          |                                                  |                                                                         |                                                                            |                                                  |
|          |          |                                                  |                                                                         | [Handout](../modules/00-Introduction/lectures/Lecture-0-3/handout-0-3.qmd) |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 5        | 9/11     | Probabilsitic models with single variables       |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 6        | 9/16     | Multi-variate analysis                           |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 7        | 9/18     | Principles for multivariate visualization        |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 8        | 9/23     | Data wrangling, joins                            |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 9        | 9/25     | Trendlines and regression                        |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 10       | 9/30     | Clustering and latent variables                  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 11       | 10/2     | Descision trees and tree visualizations          |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 12       | 10/7     | Data cleaning and missing values                 |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 13       | 10/9     |                                                  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
|          | 10/14    | Uncertainty and estimation                       |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 14       | 10/16    | Bootstrapping and simulation                     |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 15       | 10/21    | High-dimensional data, dimensionality reduction  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 16       | 10/23    | Working with timeseries data                     |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 17       | 10/28    | Timeseries visualization                         |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 18       | 10/30    | Timeseries models and analysis                   |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 19       | 11/4     | Spatial data analysis and visualization          |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 20       | 11/6     | Geographic data, projections and maps            |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 21       | 11/11    | Climate data                                     |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 22       | 11/13    | Moving to the web                                |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 23       | 11/18    | Interaction and animation pt. 1                  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 24       | 11/20    | Interaction and animation pt. 2                  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 25       | 11/25    | Network data, representations and visualizations |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
|          | 11/27    |                                                  |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 26       | 12/2     | Network analysis and layout algorithms           |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
| 27       | 12/4     | Network modeling                                 |                                                                         |                                                                            |                                                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
|          | 12/9     |                                                  |                                                                         |                                                                            | **Final Project Due (11:59pm)**                  |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+
|          | 12/13    |                                                  |                                                                         |                                                                            | **Final Reflections and Feedback Due (11:59pm)** |
+----------+----------+--------------------------------------------------+-------------------------------------------------------------------------+----------------------------------------------------------------------------+--------------------------------------------------+