---
title: "Homework 2: Exploring relationships in data"
subtitle: Data Analytics and Visualization, Fall 2024
author: Prof. Gabe Hope
institute: Harvey Mudd College
date: August 2024
format: html
---

# Learning objectives
- Practice locating and accessing a dataset of interest
- Join multiple datasets using Pandas
- Visualize multiple variables simultaniously
- Understand how to create effective and accessible visualizations
- Filter and aggregate data to find information about subpopulations
- Justify your descisions
- Practice publishing a report using Quarto

# Logistics

## Timeline
- **Friday, October 18 11:59pm** Create a gradescope submission for your assignment with all group members.
- **Friday, October 25 11:59pm** Submit your final assignment on Gradescope
- **Friday, October 25 11:59pm** Submit your reflections on Gradescope.
- **Tuesday, October 29 11:59pm** Submit your peer feedback on Gradescope.

## Groups
This assignment **must** be completed in groups of 2-3 students. You are free to switch groups from previous assignments if you'd like. The instructor reserves the right to add students to a group as needed.

Once you have chosen your group, please create a submission on Gradescope with all group memebers by **Friday, September XX**. 

# Assignment

**Goal:** In this assignment, you'll put yourselves in the shoes of a *data journalist* (perhaps working somewhere like FiveThirtyEight or the Upshot). Your goal is to create some eye-catching, informative visualizations that will entice readers to your site (while also educating them!) and justify the descisions you made in creating these visualizations to convince your editor to put them on the front page. You'll use the *multi-variable* analysis and visualization techniques that we've learned in class to make your case.

To start, choose a public dataset **as a group**. You're welcome to continue using the same dataset from the previous assignment or to choose a new one. Your chosen dataset should have a **minimum of 3-5 variables** including **at least one nominal variable** and **at least 2 ordinal or continuous variables**. If your dataset does not have enough varibles for your analysis of interest, you may **join** 2 or more datasets as discussed in class.  

**Each member** of your team should create at least one visualization using two or more variables that illustrates some interesting structure of the data. **Each visualization should be a distinct** both in terms of the variables being shown *and* the visualization techniques used. At least one visualization should encode **3 or more variables** (including at least one nominal variable) and at least one visualization should involve **grouping/aggregating** the data in some way.

:::{.callout-note}
There may be overlap in the variables and/or techniques used across plots, as long as there is some noteable distinction in each case. For example, it is *not* sufficient to produce 2-3 scatterplots of different pairs of variables, nor is it sufficient to simply plot the same (untransformed) variables as a scatterplot and a density plot.
:::

In designing your visualizations, you should focus on the following qualities from the visualization rubric:

- **Motivation:** Does my visualization reveal something non-obvious about my data? Would a reader find it interesting or exciting?
- **Completeness:** Does my visualization show the most important and/or relevant relationships between variables in my dataset? Does my visualization leave out any factors that might help further explain the information shown?
- **Interpretability:** What kinds of questions could a reader answer using my visualization? How difficult would it be to parse the answers to these questions from the visualization?
- **Aesthetics:** Is my visualization eye-catching and aesthetically pleasing? Does it appropriately convey any emotion that I'd like my reader to take from it?
- **Acessibility:** Is my visualization acessable? It it clear, easy to read, even for readers with visual impairments?

**Submit a 1-3 page (including figures) report** about your visualizations. Your report should be written for a someone (like a data journalism editor) with knowledge of data analytics and visualization, to convince them of the merits of your visualizations. This means, as in the first assignment, you should first motivate *why* your chosen dataset is interesting/exciting/important. Then explain what your visualizations show about the data. Make sure to justify *why* you chose to show the variables you did, and *why* you think each plot type you chose is most appropriate for visualizing those particular variables. Also make sure to justify any choices you made with respect to colors, scales or labeling. Finally, give concrete examples of what a reader could take away from your visualizations, e.g. what questions a reader might have about a subject that could be answered by your visualization.


## Requirements checklist

- [ ] Choose a public dataset to focus on. In your report motivate *why* you find this dataset interesting.
    - [ ] You *may* choose to join 2 or more datasets.
- [ ] Create 1 visualization for **each team member**. Every chosen variable should have a visualization that shows its distribution. 
    - [ ] 1 visualization should include at least 3 variables (at least 1 being nomial).
    - [ ] 1 visualization should involve grouping/aggregating the data.
- [ ] Submit a report that: **introduces and motivates the chosen dataset**, **shows and discusses your visualizations**, and **discuses your analysis of the visualizations**.

## Format and submission

Assignments should follow the homework [Quarto/Jupyter template](https://github.com/gabehope/DataViz-Homework-Template). Each submission should be rendered as HTML and submitted through Canvas. Submission page is available [here](https://harveymuddcollege.instructure.com/courses/1728/assignments/10319).

## Rubric

Both peer and intstructor feedback will use the following rubric for assesment.

## Reflections
Individual reflections are due on Gradescope within 1 day of submitting the final assignment. Each reflection will ask the following questions. 

- How long did you spend on this assignment?
- What did you contribute in working on this assignment? Is there anything you are proud of or think you could have done better?
- Did each group member contribute (roughly) equally to this assignment?
- Do you have any feedback for the instructor about how this assignment could be improved? (Or any other issues with the course?)
- Did you recieve any particular peer or instructor feedback that you felt helped you produce a better submission?

The goal of reflections is to help you think about your progress throughout this course and to help the instructor identify any potential issues. They will be much more helpful if you answer honestly. Reflections will only be graded based on completion, **not** on content and responses will **not** be shared with your peers. You should **not spend more than 5 minutes** completing the reflection.

## Peer feedback

Once the assignment has been completed you will be assigned to provide feedback on the submission of one of your peers. Peer feedback must be submitted on Gradescope within 1 week of the assignment due date. You should aim to spend **10-20 minutes** providing feedback.

Please also refer to the guidelines for effective feedback.

:::{.callout-note}
While your options are valued and may be referenced in instructor feedback, peer feedback will not be directly used to determine assignment grades.
:::

## Time estimates

Below is a (rough) outline of how much time each team member should aim to work on each part of this assignment. If you find that any part of this assingment is taking considerably longer, please reach out to the instructor.

- **Choosing a dataset and variables:** 30 minutes.
- **Creating a visualization:** up to 60 minutes.
- **Writing the report:** up to 60 minutes.
- **Reflections and peer feedback:** <30 minutes.

**Total:** 3-4 hours

# Tips, tricks and suggestions

As with the previous assignment, this assignment is **intentionally open-ended**. You're encouraged to follow your curiosity in the datasets and analysis you choose to focus on. Remember that grading will be focused on whether or not you follow the principles outlined in the rubric, *not* whether you picked the best possible dataset, visualization, model or report format.

Below is a guide for how you *could* approach this assignment. You don't need to follow it exactly; you're free to do whatever visualizations and analysis you'd like as long as they fall within the requirements outlined above.

## Part 1: Finding a dataset

The same advice for choosing a dataset applies to this assignment! Recall the tips below:

- **Choose data that interests you!** For example, if you are a baseball fan, you could consider a dataset of player stats from the Lehman database. If you're interested in public health, you could consider COVID data from sources like the CDC or CA/NY open data repositories.
- **Consider the format!** Data formated in the CSV (or similar like TSV, XLSX, etc.) format will be the easiest to work with for this assignment and many data sources provide data in this format. Data that requires specialized formats or access via an API may require more time than you'd want to spend.
- **Keep it a managable size!** In many cases you'll find datasets with thousands, millions or even possibly *billions* of observations. If the dataset you chose is too large, you may have quite a bit of difficulty visualizing and analyzing it with the tools we are using in this course. Try to restrict your data to have fewer than ~10,000 observations, and it's completely fine if your dataset only has as few as 30-50 observations. For example, if you are considering using the Stanford open policing project, you might choose only the data from a particular small city such as Little Rock.
- **Choose multifaceted data!** For the rest of this assignment you'll be asked to analyze different types of variables within your chosen data. Make sure to choose a dataset that has enough diversity in its variables to answer these questions. Otherwise you may need to use more than one dataset.

Once you've chosen your data, download it an make sure every team member has access. 

**Load your data into Python using Pandas.** You should be able to verify that it loaded correctly using something like `df.head()`. Then make sure you understand what the data represents. You should be able to answer the following questions: *How many variables are in the dataset? What is the type of each variable and what does it represent? How many observations are in the dataset and what does each one represent?*

**Be careful when joining datasets!** It will often be useful to combine data from multiple files, as shown in quiz 2. However you should be careful when doing so. Make sure the variable you are joining on has the same *meaning* in both data sources. If possible, it's a good idea to stick to combining datasets from the same source. In the example in quiz 2, both datasets are from the Gapminder organization. 


## Part 2: Create (and iterate on) your visualizations

Use Let's plot or your favorite visualization library to create the required visualizations. 

**Delegate tasks as a group.** Before creating individual visualizations, make sure all group members are in agreement about what you'd like to show in each visualization and that the requirements outlined about will be met.

**Iterate on your visualizations.** Make sure that each visualization that you create is *effective* and *expressive*. This might mean trying out different geometries, scales, coordinate systems or mappings. Find a visualization that says something interesting about the chosen dataset.

**Discuss as a group.** Solicit feedback from your group memebers as you go. Make sure that other can understand what a given visualization is showing.

## Part 3: Writing up!

Finally, once your visualization an analysis is complete you'll need to write up a report on what you found. Consider why you chose the data that you did and what you were hoping to find. Did your visualization show this? How do your visualizations meet the goals of *effectiveness* and *expressiveness*? Is there anything you would have liked to improve?


